# Generated by Django 3.1.4 on 2020-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcat_name',
            field=models.CharField(default='This is name', max_length=250),
            preserve_default=False,
        ),
    ]
