# Generated by Django 3.1.3 on 2020-12-09 14:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20201207_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info_list',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
