# Generated by Django 3.1.3 on 2020-12-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20201209_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='user_category',
            new_name='category',
        ),
    ]
