# Generated by Django 3.1.3 on 2020-12-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20201210_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='user_category',
        ),
    ]
